/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PERIPHERALS_H_
#define _PERIPHERALS_H_

/***********************************************************************************************************************
 * Included files
 **********************************************************************************************************************/
#include "fsl_common.h"
#include "fsl_pit.h"
#include "fsl_uart.h"
#include "fsl_clock.h"
#include "fsl_ftm.h"

#if defined(__cplusplus)
extern "C" {
#endif /* __cplusplus */

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/
/* Definitions for BOARD_InitPeripherals functional group */
/* BOARD_InitPeripherals defines for PIT */
/* Definition of peripheral ID. */
#define PIT1_PERIPHERAL PIT
/* Definition of clock source. */
#define PIT1_CLOCK_SOURCE kCLOCK_BusClk
/* Definition of clock source frequency. */
#define PIT1_CLK_FREQ CLOCK_GetFreq(PIT1_CLOCK_SOURCE)
/* Definition of ticks count for channel 0. */
#define PIT1_0_TICKS USEC_TO_COUNT(5000U, PIT1_CLK_FREQ) - 1U
/* PIT1 interrupt vector ID (number). */
#define PIT1_0_IRQN PIT0_IRQn
/* PIT1 interrupt handler identifier. */
#define PIT1_0_IRQHANDLER PIT0_IRQHandler
/* Definition of peripheral ID */
#define UART_AUX_PERIPHERAL UART0
/* Definition of the clock source frequency */
#define UART_AUX_CLOCK_SOURCE CLOCK_GetFreq(UART0_CLK_SRC)
/* Rx transfer buffer size. */
#define UART_AUX_RX_BUFFER_SIZE 10
/* Tx transfer buffer size. */
#define UART_AUX_TX_BUFFER_SIZE 10
/* Definition of peripheral ID */
#define QUAD1_PERIPHERAL FTM2
/* Definition of the clock source frequency */
#define QUAD1_CLOCK_SOURCE CLOCK_GetFreq(kCLOCK_BusClk)
/* QUAD1 interrupt vector ID (number). */
#define QUAD1_IRQN FTM2_IRQn
/* QUAD1 interrupt handler identifier. */
#define QUAD1_IRQHANDLER FTM2_IRQHandler

/***********************************************************************************************************************
 * Global variables
 **********************************************************************************************************************/
extern const pit_config_t PIT1_config;
extern const uart_config_t UART_AUX_config;
extern uart_handle_t UART_AUX_handle;
extern uint8_t UART_AUX_rxBuffer[UART_AUX_RX_BUFFER_SIZE];
extern const uart_transfer_t UART_AUX_rxTransfer;
extern uint8_t UART_AUX_txBuffer[UART_AUX_TX_BUFFER_SIZE];
extern const uart_transfer_t UART_AUX_txTransfer;
extern const ftm_config_t QUAD1_config;

/***********************************************************************************************************************
 * Initialization functions
 **********************************************************************************************************************/
void BOARD_InitPeripherals(void);

/***********************************************************************************************************************
 * BOARD_InitBootPeripherals function
 **********************************************************************************************************************/
void BOARD_InitBootPeripherals(void);

#if defined(__cplusplus)
}
#endif

#endif /* _PERIPHERALS_H_ */
